/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 massa.gltf
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function MassaModel(props) {
  const { nodes, materials } = useGLTF('/public/models/massa.gltf')
  const [materialColor, setMaterialColor] = useState("#0F1318")

  const handleColor=()=>{
    materialColor ===  "#0F1318" ? setMaterialColor("#e74e4e") : setMaterialColor("#0F1318");

  }

  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes.Icosphere.geometry} 
      material={materials['Material.001']} 
      material-color={materialColor} 
      onPointerEnter={
        ()=>handleColor()
        }
      onPointerLeave={
        ()=>handleColor()
      }
      />
    </group>
  )
}

useGLTF.preload('/massa.gltf')
