/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 massaTextNode.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MassaTextNode(props) {
  const { nodes, materials } = useGLTF('/public/models/massaTextNode.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} position={[-2.78, -0.55, 4.53]} rotation={[Math.PI / 2, 0, 0.89]} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.002']} position={[-5.9, -1.07, 0.35]} rotation={[Math.PI / 2, 0, 1.6]} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.002']} position={[-2.97, -1.53, -4.42]} rotation={[Math.PI / 2, 0, 2.48]} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.002']} position={[2.91, -2.57, -4.44]} rotation={[Math.PI / 2, 0, -2.35]} />
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.002']} position={[5.93, -3.06, -0.24]} rotation={[Math.PI / 2, 0, -1.59]} />
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.002']} position={[2.96, -3.66, 4.43]} rotation={[Math.PI / 2, 0, -0.62]} />
      <mesh geometry={nodes.sphereCenter2.geometry} material={materials['Material.002']} scale={0.31} />
      <mesh geometry={nodes.sphereCenter1.geometry} material={materials['Material.006']} scale={0.28} />
    </group>
  )
}

useGLTF.preload('/massaTextNode.gltf')
